packages:
  - .

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@apidevtools/json-schema-ref-parser@15.3.6'

packageExtensions:
  json-schema-walker@*:
    dependencies:
      "@types/json-schema": ^7.0.15
